name: scummvm
version: stable
version-script: git -C parts/scummvm/src describe --tags | sed 's/desc\///'
summary: ScummVM
description: |
    ScummVM is a program which allows you to run certain classic graphical
    point-and-click adventure games, provided you already have their data
    files. The clever part about this: ScummVM just replaces the executables
    shipped with the game, allowing you to play them on systems for which
    they were never designed!
confinement: strict
grade: stable

apps:
  scummvm:
    command: scummvm
    plugs: [x11, home, pulseaudio, unity7, opengl]

parts:
  scummvm:
    source: https://github.com/scummvm/scummvm.git
    override-build: |
      last_committed_tag="$(git describe --tags --abbrev=0)"
      trimmed_tag="$(echo $last_committed_tag | sed 's/desc\///' | sed 's/git//' )"
      last_released_tag="$(snap info scummvm | awk '$1 == "beta:" { print $2 }')"
      # If the latest tag from the upstream project has not been released to
      # beta, build that tag instead of master.
      if [ "${trimmed_tag}" != "${last_released_tag}" ]; then
        git fetch
        git checkout "${last_committed_tag}"
      fi    
      snapcraftctl build
    plugin: autotools
#    To do a quick test build
#    configflags:
#      - --disable-all-engines
#      - --enable-engine=scumm
    build-packages:
      - g++
      - make
      - libsdl1.2-dev
      - libjpeg62-dev
      - libmpeg2-4-dev
      - libogg-dev
      - libvorbis-dev
      - libflac-dev
      - libmad0-dev
      - libpng12-dev
      - libtheora-dev
      - libfaad-dev
      - libfluidsynth-dev
      - libfreetype6-dev
      - zlib1g-dev
      - libunity-dev
    stage-packages:
      - libicu55
      - libasound2
      - libc6
      - libfaad2
      - libflac8
      - libfluidsynth1
      - libgl1-mesa-dri
      - libgl1-mesa-glx
      - libjpeg62
      - libjpeg8
      - libmad0
      - libmpeg2-4
      - libogg0
      - libpng12-0
      - libsdl1.2debian
      - libsndio6.1
      - libstdc++6
      - libtheora0
      - libvorbis0a
      - libvorbisfile3
      - zlib1g
